### ISSUE TITLE
MindsDB asks for re-training the GPT model

### ISSUE THREAD

**Issue by lnxpy** [lnxpy/hey#2]
* Hey version: 0.1.0
* Python version: 3.11.2
* Operating System: MacOS

### Description

`mindsdb_sdk` asks for a retrain on the GPT model on the dashboard. Its exception only needs to be handled in a better more-detailed way.

### What I Did

```
$ hey something..
Traceback (most recent call last):
  File "/opt/homebrew/bin/hey", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/hey/cli.py", line 85, in main
    console.print(instance.answer(
                  ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/hey/middlewares/mindsdb.py", line 86, in answer
    ).fetch()
      ^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mindsdb_sdk/query.py", line 29, in fetch
    return self.api.sql_query(self.sql, self.database)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mindsdb_sdk/connectors/rest_api.py", line 11, in wrapper
    return fnc(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/mindsdb_sdk/connectors/rest_api.py", line 78, in sql_query
    raise RuntimeError(data['error_message'])
RuntimeError: model 'gpt_model' is obsolete and needs to be updated. Run 'RETRAIN gpt_model;'
```

**Comment by lnxpy** [comment]
It's an issue with MindsDB and not Hey. You have to check on your MindsDB dashboard and retrain your model to fix the problem.
