### ISSUE TITLE
I got error on asking first question.

### ISSUE THREAD

**Issue by masoodkamyab** [lnxpy/hey#3]
* Hey version: v0.1.0
* Python version: 3.10.6
* Operating System: ubuntu 22.04

### Description

Hey, I got this error when I asked the first question after I added my authentication:
```
Traceback (most recent call last):
  File "/home/masood/.local/bin/hey", line 8, in <module>
    sys.exit(main())
  File "/home/masood/.local/lib/python3.10/site-packages/hey/cli.py", line 85, in main
    console.print(instance.answer(
  File "/home/masood/.local/lib/python3.10/site-packages/hey/middlewares/mindsdb.py", line 86, in answer
    ).fetch()
  File "/home/masood/.local/lib/python3.10/site-packages/mindsdb_sdk/query.py", line 29, in fetch
    return self.api.sql_query(self.sql, self.database)
  File "/home/masood/.local/lib/python3.10/site-packages/mindsdb_sdk/connectors/rest_api.py", line 11, in wrapper
    return fnc(self, *args, **kwargs)
  File "/home/masood/.local/lib/python3.10/site-packages/mindsdb_sdk/connectors/rest_api.py", line 78, in sql_query
    raise RuntimeError(data['error_message'])
RuntimeError: Can't find view with name/id: gpt_model/None
```

**Comment by lnxpy** [comment]
Hey!
It looks like your GPT model is not trained/prepared properly on MindsDB. Would you please provide an image of your dashboard and the list of tables within the `mindsdb` database?
